name: CI

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  build_and_test:
    runs-on: ubuntu-latest
    steps:
      - name: Clonar el repositorio
        uses: actions/checkout@v2

      # Si tienes submódulos:
      - name: Actualizar submódulos
        run: git submodule update --init --recursive

      # Instalar dependencias (ejemplo con Node.js)
      - name: Configurar Node.js
        uses: actions/setup-node@v3
        with:
          node-version: '14'

      - name: Instalar dependencias
        run: npm install

      - name: Ejecutar pruebas
        run: npm test
